// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAysTPKWPp6J0-Gko4A3fUV57GXbg60axA',
    appId: '1:898123623832:web:e56f8c63bb4c550b6c8fed',
    messagingSenderId: '898123623832',
    projectId: 'task-manage-fb25',
    authDomain: 'task-manage-fb25.firebaseapp.com',
    storageBucket: 'task-manage-fb25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoM6wZgcP7xx4WIRz5qezDUbrep7pkvHA',
    appId: '1:898123623832:android:e1ed6490738787e86c8fed',
    messagingSenderId: '898123623832',
    projectId: 'task-manage-fb25',
    storageBucket: 'task-manage-fb25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAViS6DToeNPugEXlew1dPOTVtRMXeokc',
    appId: '1:898123623832:ios:20e959a6f67917c36c8fed',
    messagingSenderId: '898123623832',
    projectId: 'task-manage-fb25',
    storageBucket: 'task-manage-fb25.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAViS6DToeNPugEXlew1dPOTVtRMXeokc',
    appId: '1:898123623832:ios:20e959a6f67917c36c8fed',
    messagingSenderId: '898123623832',
    projectId: 'task-manage-fb25',
    storageBucket: 'task-manage-fb25.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAysTPKWPp6J0-Gko4A3fUV57GXbg60axA',
    appId: '1:898123623832:web:a418d2afdb8ea97a6c8fed',
    messagingSenderId: '898123623832',
    projectId: 'task-manage-fb25',
    authDomain: 'task-manage-fb25.firebaseapp.com',
    storageBucket: 'task-manage-fb25.firebasestorage.app',
  );
}
